[package]
name = "pgpq"
version = "0.1.0"
edition = "2021"
description = ""

[dependencies]
byteorder = "^1.4.3"
bytes = "^1.4.0"
chrono = "^0.4.23"
arrow-schema = "^32.0.0"

[dependencies.postgres-types]
version = "^0.2.4"
features = [
    "with-bit-vec-0_6",
    "with-chrono-0_4",
    "with-time-0_3",
    "with-uuid-1",
    "with-time-0_3",
    "with-eui48-1",
]

[dependencies.arrow]
version = "^32.0.0"
default-features = false
features = ["chrono-tz"]

[dependencies.arrow-array]
version = "^32.0.0"
default-features = false
features = ["chrono-tz"]

[dev-dependencies]
rstest = ">=0.16.0"
parquet = ">=32.0.0"
criterion = ">=0.4.0"

[[bench]]
name = "benchmarks"
harness = false
